apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      {{- if hasKey .Values.wordpress.image "pullSecrets" }}
      imagePullSecrets:
        - name: {{ .Values.wordpress.image.pullSecrets.name }}
      {{- end }}
      containers:
        - name: varnish
          image: {{ .Values.varnish.image.name }}
          imagePullPolicy: {{ .Values.varnish.image.pullPolicy }}
          env:
            - name: REMOTE_HOST
              value: wordpress-service
            - name: REMOTE_PORT
              value: "8080"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"