apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - host: {{ .Values.wordpress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: varnish-service
                port:
                  number: 80