version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH wordpress/docker
      - run:
          name: Push Docker image
          command: |
            IMAGE_ID=$(docker images -q $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH)
            IMAGE_TAG=ghcr.io/$GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH
            echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker tag $IMAGE_ID $IMAGE_TAG
            docker push $IMAGE_TAG
  deploy-k8s:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: test
          command: |
            echo -n $KUBECONFIG_DATA | base64 --decode
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run:
          name: Deploy To Kubernetes
          command: |
            kubectl get pods --all-namespaces
workflows:
  pipeline:
    jobs:
      # - build-docker-image
      # - deploy-k8s:
      #     requires:
      #       - build-docker-image
      - deploy-k8s

