version: 2.1
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $GITHUB_USERNAME/wordpress:$TAG wordpress/docker
      - run:
          name: Push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            IMAGE_ID=$(docker images -q $GITHUB_USERNAME/wordpress:$TAG)
            echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker tag $IMAGE_ID ghcr.io/$GITHUB_USERNAME/wordpress:$TAG
            docker push ghcr.io/$GITHUB_USERNAME/wordpress:$TAG
workflows:
  pipeline:
    jobs:
      - build-docker-image
