version: 2.1
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
        auth: # For spin up a Docker daemon
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH wordpress/docker
      - run:
          name: Push Docker image
          command: |
            IMAGE_ID=$(docker images -q $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH)
            IMAGE_TAG=ghcr.io/$GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH
            echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker tag $IMAGE_ID $IMAGE_TAG
            docker push $IMAGE_TAG
workflows:
  pipeline:
    jobs:
      - build-docker-image
