version: 2.1
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: $GITHUB_USERNAME/wordpress:{{ .Branch }}
    steps:
      - run:
          command: echo $IMAGE_NAME
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME wordpress/docker
      - run:
          name: Push Docker image
          command: |
            IMAGE_ID=$(docker images -q $IMAGE_NAME)
            echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker tag $IMAGE_ID ghcr.io/$IMAGE_NAME
            docker push ghcr.io/$IMAGE_NAME
workflows:
  pipeline:
    jobs:
      - build-docker-image
