version: 2.1
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2023.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH wordpress/docker
      - run:
          name: Push Docker image
          command: |
            IMAGE_ID=$(docker images -q $GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH)
            echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker tag $IMAGE_ID ghcr.io/$GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH
            # docker push ghcr.io/$GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH
            echo "ghcr.io/$GITHUB_USERNAME/wordpress:$CIRCLE_BRANCH"
workflows:
  pipeline:
    jobs:
      - build-docker-image
