apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
data:
  admin-user: {{ .Values.wordpress.admin_user | b64enc }}
  admin-password: {{ .Values.wordpress.admin_password | b64enc }}
  title: {{ .Values.wordpress.title | b64enc }}