apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
data:
  admin-user: {{ .Values.wordpress.admin_user | b64enc }}
  admin-password: {{ .Values.wordpress.admin_password | b64enc }}
  title: {{ .Values.wordpress.title | b64enc }}

{{- if hasKey .Values.wordpress.image "pullSecrets" }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.wordpress.image.pullSecrets.name }}
  labels:
    app: wordpress
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWFJwYm5ObFlYVTZaMmh3WHpCcVoyaHVRblYyTkVFNGJtVk1XWEprWkdFM1NURTJVelZwYzFwemFqQlNTRTVsVVE9PSJ9fX0i
{{- end}}